language: php

php:
  - 5.4
  - 5.5

before_script:
  - composer self-update
  - composer install --dev

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/phpcs --standard=PSR2 ./src/ ./test

after_script:
  - php vendor/bin/coveralls -v
